export { default as About } from './About.tsx';
export { default as Contact } from './Contact.tsx';
export { default as Error } from './Error.tsx';
export { default as Home } from './Home.tsx';
export { default as Login } from './Login.tsx';
export { default as Profile } from './Profile.tsx';
export { default as Projects } from './Projects.tsx';
export { default as Students } from './Students.tsx';
export { default as Workshops } from './Workshops.tsx';